management_prj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from  django.conf.urls.static import static

urlpatterns = [
    path('teamangel/', include('teamangel.urls')),
    path("admin/", admin.site.urls),
    path('', include('single_pages.urls')), #대문페이지
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

teamangel/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('delete_comment/<int:pk>/', views.delete_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),
    path('category/<str:slug>/', views.category_page),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('', views.PostList.as_view()),

]

teamangel/models.py
import os

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/teamangel/category/{self.slug}/'

    class Meta:
        verbose_name_plural = 'Categories'
class Post(models.Model):
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True)
    content = models.TextField()

    head_image = models.ImageField(upload_to='teamangel/images/%Y/%m/%d', blank=True)  # 이미지 폴더 지정하기

    file_upload = models.FileField(upload_to='teamangel/files/%Y/%m/%d', blank=True)  # 포스트에 파일 올리기
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    views = models.PositiveIntegerField(default=0)


    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/teamangel/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]  # -1의미는 확장자 의미를함 EX) ~~.html txt py doc csv

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'
class PostImage(models.Model):
    image = models.ImageField(upload_to='teamangel/images/%Y/%m/%d')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')

teamangel/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta: # ModelForm에서 상속받은 경우에 있어야 함.
        model = Comment
        fields = ('content', )

teamangel/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect
from .forms import CommentForm

from .models import Post, Category, Comment, PostImage
from django.views.generic import ListView, DetailView, CreateView, UpdateView


class PostList(ListView):
    model = Post
    ordering = '-pk' #ListView로 포스트 목록 페이지 만들기
    paginate_by = 4
    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()  # post_list
        context['categories'] = Category.objects.all()
        context['comment_form'] = CommentForm
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        context['posts_by_views'] = Post.objects.all().order_by('-views')[:4]  # 조회수가 높은 게시글 5개
        return context  # -> post_list.html

def category_page(request, slug):
    if slug == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)

    # 페이지네이션 설정
    paginator = Paginator(post_list, 4)  # 페이지당 4개의 포스트 표시
    page = request.GET.get('page')
    post_list = paginator.get_page(page)

    is_paginated = post_list.has_other_pages()

    return render(
        request,
        'teamangel/category.html',
        {
            'categories': Category.objects.all(),
            'no_category_post_count': Post.objects.filter(category=None).count(),
            'category': category,
            'post_list': post_list,
            'is_paginated': is_paginated,  # 추가
            'page_obj': post_list,  # 추가
            'paginator': paginator,
        }
    )



class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()

        return context

    def get_object(self):
        obj = super().get_object()
        obj.views += 1  # 조회수 증가
        obj.save()
        return obj


class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'category', 'head_image', 'file_upload']
    template_name = 'teamangel/post_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def get_context_data(self, **kwargs):
        context = super(PostUpdate, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()

        # 여러 이미지 저장
        for file in self.request.FILES.getlist('images'):
            PostImage.objects.create(image=file, post=post)

        return super().form_valid(form)



class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'category', 'head_image', 'file_upload']

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def get_context_data(self, **kwargs):
        context = super(PostCreate, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()

        # 여러 이미지 저장
        for file in self.request.FILES.getlist('images'):
            PostImage.objects.create(image=file, post=post)

        return super().form_valid(form)


def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)

        if request.method == "POST":
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
            else:
                return redirect(post.get_absolute_url())
        else:
            raise PermissionDenied

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    # comment_form.html

    def dispath(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispath(request, *args, **kwargs)
        else:
            raise PermissionDenied
def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

teamangel/templates/teamangel/post_detail.html
<!doctype html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ post.title }} - Cheonnan Site</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
	<link rel="stylesheet" href="{% static 'teamangel/assets/css/main.css' %}" media="screen">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="{% static 'teamangel/assets/css/main.css' %}" media="screen">
    <style>
        .post-images {
            display: flex;
            overflow-x: auto; /* 좌우 스크롤바 허용 */
            overflow-y: hidden; /* 위아래 스크롤바 숨기기 */
            width: 100%;
            white-space: nowrap; /* 줄바꿈 방지 */
        }

        .post-images img {
            flex: 0 0 auto;
            width: 10%;
        }
        .post-images img {
			flex: 0 0 auto;
			margin-right: 10px; /* 오른쪽에 20px 간격 추가 */
		}
    </style>
</head>

<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<div id="main">
						<div class="inner">

							<!-- Header -->
								<header id="header">
									<a href="/teamangel/" class="logo"><strong>HOME PAGE</strong></a>
									<ul class="icons">

										{% if user.is_authenticated %}
											<li><a href="{% url 'account_logout' %}" class="button primary small">Logout</a></li>
										{% else %}
											<li><a href="{% url 'account_login' %}" class="button small">Login</a></li>
										{% endif %}
										<li><a href="https://www.youtube.com/channel/UC893trfAnCUjJcbPE9z6XWA" class="icon brands fa-youtube"><span class="label">YouTube</span></a></li>
										<li><a href="https://www.facebook.com/people/%EC%B2%9C%EC%95%88%EC%82%AC%EC%9D%B4%ED%8A%B8/61551860214367/?mibextid=ZbWKwL" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
										<li><a href="https://www.instagram.com/cheonansite/" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
									</ul>
								</header>


							<!-- Conwtent -->
								<section>
									<header class="main">
										{% if user.is_authenticated and user == post.author %}
											<a class="btn btn-info btn-sm float-right" href="/teamangel/update_post/{{ post.pk }}/" role="button"><i class ="fas fa-pen"></i>Edit Post</a>
										{% endif %}
										<h1>{{ post.title }}</h1>
										<h5>{{ post.hook_text }}</h5> <!-- 클래스 수정하기 -->
                                        <h4>{{ post.created_at }}</h4>
									</header>
									{% if post.head_image %}
									<span class="image main"><img src="{{ post.head_image.url}}" alt="{{ post }} head-image" /></span>
									{% else %}
									<span class="image main" src="https://picsum.photos/seed/{{post.id}}/800/200" alt="random-image"></span>
									{% endif %}
									<hr class="major" />
									<!-- 연결된 이미지들 표시 -->
									<div class="post-images">
										{% for post_image in post.images.all %}
											<img src="{{ post_image.image.url }}" alt="Post Image" style="width: 40%;">
										{% endfor %}
									</div>
									<hr class="major" />

									<h2>POST CONTENTS</h2>
									<p>{{ post.content| linebreaks }}</p>
									<hr class="major" />
<!--									<hr class="major" />--파일 업로드>
<									{% if post.file_upload %}-->
<!--									<a href="{{ post.file_upload.url }}" class="btn btn-primary" role="button" download>-->
<!--										{% if post.get_file_ext == 'csv' %}-->
<!--											<i class="fas fa-file-csv"></i>-->
<!--										{% elif post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}-->
<!--											<i class="fas fa-file-excel"></i>-->
<!--										{% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc' %}-->
<!--											<i class="fas fa-file-word"></i>-->
<!--										{% else %}-->
<!--											<i class="fas fa-file"></i>-->
<!--										{% endif %}-->
<!--										Download {{ post.get_file_name }}-->
<!--									</a>-->
								{% endif %}

									<hr class="major" />



									<!-- Comment -->
									{% if user.is_authenticated %}
									<form id="comment-form" method="POST" action="{{ post.get_absolute_url }}new_comment/">
										{% csrf_token %}
										<div class="col-12">
											<textarea name="content" id="demo-message" placeholder="Enter your message" rows="6">{{ comment_form.content }}</textarea>
										</div>
										<!-- Break -->
										<div class="col-12">
											<ul class="actions">
												<li><input type="submit" value="Submit" class="primary" /></li>
											</ul>
										</div>
									</form>

									{% else %}
									<div class="col-6 col-12-small">
										<ul class="actions stacked">
											<li>
												<a href="#" class="button small fit btn btn-outline-dark btn-block btn-sm"
													data-toggle="modal" data-target="#loginModal">Log In and leave a comment</a>
											</li>
										</ul>
									</div>
									{% endif %}

									{% if post.comment_set.exists %}
										{% for comment in post.comment_set.iterator %}
										<div class="media mb-4" id="comment- {{ comment.pk }}">
											<img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50*50" alt="">
											<div class="media-body">
												<h5 class="mt-0">{{	comment.author.username }} &nbsp;&nbsp;<small class="text-muted">
													{{ comment.created_at }}</small>
												</h5>
												<p>{{ comment.content | linebreaks }}</p>
												{% if comment.created_at != comment.modified_at %}
													<p class="text-muted float-right"><small>Updated: {{comment.modified_at}}</small></p>
												{% endif %}
												{% if user.is_authenticated and comment.author == user %}
													<a class="btn btn-sm btn-info button primary" role="button" id="comment-{{ comment.pk }}-update-btn" href="/teamangel/update_comment/{{comment.pk}}/">
														<small>Edit</small>
													</a>

													<a class="btn btn-sm btn-danger button" role="button" id="comment-{{ comment.pk }}-delete-modal-btn" href="/teamangel/delete_comment/{{comment.pk}}">
														<small>Delete</small>
													</a>
												{% endif %}
											</div>
										</div>

										{% endfor %}
									{% endif %}
								</section>
								{% if is_paginated %}
							<!-- Pagination-->
							<div style="width: 100%; text-align: center;  bottom: 0px;">
									<ul class="pagination" style="left: 0; right: 0">
										{% if page_obj.has_previous %}
											<li class="page-item">
												<a class="page-link button" href="?page={{ page_obj.previous_page_number }}">&larr; Prev</a>
											</li>
										{% else %}
											<li class="page-item disabled">
												<span class="page-link button">&larr; Prev</span>
											</li>
										{% endif %}

										{% for i in paginator.page_range %}
											{% if i == page_obj.number %}
											<li class="page-item active">
												<a class="page" href="?page={{ i }}">{{ i }}</a>
											</li>
											{% else %}
											<li class="page-item">
												<a class="page" href="?page={{ i }}">{{ i }}</a>
											</li>
											{% endif %}
											{% endfor %}

										{% if page_obj.has_next %}
											<li class="page-item">
												<a class="page-link button" href="?page={{ page_obj.next_page_number }}">Next &rarr;</a>
											</li>
										{% else %}
											<li class="page-item disabled">
												<span class="page-link button">Next &rarr;</span>
											</li>
										{% endif %}
									</ul>
							</div>
							{% endif %}
						</div>
					</div>

				<!-- Pagination-->


			<!-- Sidebar -->
					<div id="sidebar">
						<div class="inner">

							<!-- Search -->
								<section id="search" class="alt">
									<form method="get" action="https://search.naver.com/search.naver" target="_blank">
										<input type="text" name="query" id="query" placeholder="Press Enter" />
									</form>
								</section>
							<!-- Menu -->
							<nav id="menu">
								<header class="major">
									<h2>Menu</h2>
								</header>
								<ul>
									<li><a href="/teamangel/">Homepage</a></li>
									{% for category in categories %}
										{% if not category.parent %}
											<li>
												<!-- 서브카테고리가 있을 경우에만 opener를 표시 -->
												{% if category.category_set.all %}
													<span class="opener">{{ category.name }}</span>
													<ul>
														{% for subcategory in category.category_set.all %}
															<li><a href="{{ subcategory.get_absolute_url }}">{{ subcategory.name }}</a></li>
														{% endfor %}
													</ul>
												{% else %}
													<a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
												{% endif %}
											</li>
										{% endif %}
									{% endfor %}
								</ul>
							</nav>
							<!-- Section -->
								<section>
									<header class="major">
										<h2>Get in touch</h2>
									</header>
									<h5>비즈니스 제의 및 의견 공유는 아래로 해주세요.</h5>
									<ul class="contact">
										<li class="icon solid fa-envelope">youniyamii@gamil.com</a></li>
										<li class="icon solid fa-phone">+82-10-7628-6477</li>
										<li class="icon solid fa-home">1234 Somewhere Road<br />
										충청남도 천안시 동남구 상명대길 31</li>
									</ul>
								</section>

						</div>
					</div>
			</div>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/browser.min.js"></script>
			<script src="assets/js/breakpoints.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>
			<script>
				let startX;
				let scrollLeft;

				const slider = document.querySelector('.post-images');

				slider.addEventListener('mousedown', (e) => {
					e.preventDefault();
					startX = e.pageX - slider.offsetLeft;
					scrollLeft = slider.scrollLeft;
					slider.addEventListener('mousemove', onMove);
					slider.addEventListener('mouseup', endDrag);
					slider.addEventListener('mouseleave', endDrag);
				});

				function onMove(e) {
					const x = e.pageX - slider.offsetLeft;
					const walk = (x - startX);
					slider.scrollLeft = scrollLeft - walk;
				}

				function endDrag() {
					slider.removeEventListener('mousemove', onMove);
					slider.removeEventListener('mouseup', endDrag);
					slider.removeEventListener('mouseleave', endDrag);
				}
			</script>
	</body>
</html>

teamangel/templates/teamangel/post_form.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>포스트 작성</title>
    <link rel="stylesheet" href="{% static 'teamangel/assets/css/main.css' %}" media="screen"><link rel="stylesheet" href="{% static 'teamangel/assets/css/main.css' %}" media="screen">



</head>
<body class="is-preload">

    <!-- Wrapper -->
    <div id="wrapper">
        <!-- Main -->
        <div id="main">
            <div class="inner">
                <!-- Header -->
               <header id="header">
					<a href="/teamangel/" class="logo"><strong>HOME PAGE</strong></a>
					<ul class="icons">
						{% if user.is_authenticated %}
							<li><a href="{% url 'account_logout' %}" class="button primary small">Logout</a></li>
						{% else %}
							<li><a href="{% url 'account_login' %}" class="button small">Login</a></li>
						{% endif %}
						<li><a href="https://www.youtube.com/channel/UC893trfAnCUjJcbPE9z6XWA" class="icon brands fa-youtube"><span class="label">YouTube</span></a></li>
						<li><a href="https://www.facebook.com/people/%EC%B2%9C%EC%95%88%EC%82%AC%EC%9D%B4%ED%8A%B8/61551860214367/?mibextid=ZbWKwL" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
						<li><a href="https://www.instagram.com/cheonansite/" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
					</ul>
				</header>

                <!-- 포스트 작성 폼 -->
				<section>
					<header class="major">
						<h2>포스트 작성</h2>
					</header>
					<div class="content">
						<!-- 폼 시작 -->
						<form method="post" enctype="multipart/form-data">
							{% csrf_token %}
							{{ form.as_p }}
							<label for="images">이미지 업로드:</label>
							<input type="file" name="images" multiple>
							<br>
							<button type="submit" style="width: 100%; text-align: center; bottom: 0px;">저장</button>
						</form>
						<!-- 폼 끝 -->
					</div>
					<style>
						#id_title{
							text-align: center;
						}
						#id_hook_text{
							text-align: center;
						}
						#id_content {
							text-align: center;
						}
					</style>
				</section>


            </div>
        </div>
		<!--sidebar -->
		<div id="sidebar">
			<div class="inner">
						<!-- Search -->
							<section id="search" class="alt">
								<form method="get" action="https://search.naver.com/search.naver" target="_blank">
									<input type="text" name="query" id="query" placeholder="Press Enter" />
								</form>
							</section>
						<!-- Menu -->
						<nav id="menu">
							<header class="major">
								<h2>Menu</h2>
							</header>
							<ul>
								<li><a href="/teamangel/">Homepage</a></li>
								{% for category in categories %}
									{% if not category.parent %}
										<li>
											<!-- 서브카테고리가 있을 경우에만 opener를 표시 -->
											{% if category.category_set.all %}
												<span class="opener">{{ category.name }}</span>
												<ul>
													{% for subcategory in category.category_set.all %}
														<li><a href="{{ subcategory.get_absolute_url }}">{{ subcategory.name }}</a></li>
													{% endfor %}
												</ul>
											{% else %}
												<a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
											{% endif %}
										</li>
									{% endif %}
								{% endfor %}
							</ul>
						</nav>
						<!-- Section -->
							<section>
								<header class="major">
									<h2>Get in touch</h2>
								</header>
								<h5>비즈니스 제의 및 의견 공유는 아래로 해주세요.</h5>
								<ul class="contact">
									<li class="icon solid fa-envelope">youniyamii@gamil.com</a></li>
									<li class="icon solid fa-phone">+82-10-7628-6477</li>
									<li class="icon solid fa-home">1234 Somewhere Road<br />
									충청남도 천안시 동남구 상명대길 31</li>
								</ul>
							</section>
						</div>
					</div>
    </div>



    <!-- Scripts -->
    <script src="{% static 'teamangel/assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'teamangel/assets/js/jquery.min.js' %}"></script>
	<script src="{% static 'teamangel/assets/js/browser.min.js' %}"></script>
	<script src="{% static 'teamangel/assets/js/breakpoints.min.js' %}"></script>
	<script src="{% static 'teamangel/assets/js/util.js' %}"></script>
	<script src="{% static 'teamangel/assets/js/main.js' %}"></script>
</body>
</html>

teamangel/templates/teamangel/post_update_form.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>포스트 수정</title>
    <link rel="stylesheet" href="{% static 'teamangel/assets/css/main.css' %}" media="screen">

</head>
<body class="is-preload">

    <!-- Wrapper -->
    <div id="wrapper">
        <!-- Main -->
        <div id="main">
            <div class="inner">
                <!-- Header -->
               <header id="header">
					<a href="/teamangel/" class="logo"><strong>HOME PAGE</strong></a>
					<ul class="icons">
						{% if user.is_authenticated %}
							<li><a href="{% url 'account_logout' %}" class="button primary small">Logout</a></li>
						{% else %}
							<li><a href="{% url 'account_login' %}" class="button small">Login</a></li>
						{% endif %}
						<li><a href="https://www.youtube.com/channel/UC893trfAnCUjJcbPE9z6XWA" class="icon brands fa-youtube"><span class="label">YouTube</span></a></li>
						<li><a href="https://www.facebook.com/people/%EC%B2%9C%EC%95%88%EC%82%AC%EC%9D%B4%ED%8A%B8/61551860214367/?mibextid=ZbWKwL" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
						<li><a href="https://www.instagram.com/cheonansite/" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
					</ul>
				</header>

                <!-- 포스트 작성 폼 -->
                <section>
                    <header class="major">
                        <h2>포스트 수정</h2>
                    </header>
					<div class="content">
						<!-- 폼 시작 -->
						<form method="post" enctype="multipart/form-data">
							{% csrf_token %}
							{{ form.as_p }}
							<label for="images">이미지 업로드:</label>
							<input type="file" name="images" multiple>
							<button type="submit" style="width: 100%; text-align: center;  bottom: 0px;">저장</button>
						</form>
						<style>
						#id_title{
							text-align: center;
						}
						#id_hook_text{
							text-align: center;
						}
						#id_content {
							text-align: center;
						}
						</style>
						<!-- 폼 끝 -->
					</div>

                </section>

            </div>
        </div>
        <!-- Sidebar -->
					<div id="sidebar">
						<div class="inner">

							<!-- Search -->
								<section id="search" class="alt">
									<form method="get" action="https://search.naver.com/search.naver" target="_blank">
										<input type="text" name="query" id="query" placeholder="Press Enter" />
									</form>
								</section>
							<!-- Menu -->
							<nav id="menu">
								<header class="major">
									<h2>Menu</h2>
								</header>
								<ul>
									<li><a href="/teamangel/">Homepage</a></li>
									{% for category in categories %}
										{% if not category.parent %}
											<li>
												<!-- 서브카테고리가 있을 경우에만 opener를 표시 -->
												{% if category.category_set.all %}
													<span class="opener">{{ category.name }}</span>
													<ul>
														{% for subcategory in category.category_set.all %}
															<li><a href="{{ subcategory.get_absolute_url }}">{{ subcategory.name }}</a></li>
														{% endfor %}
													</ul>
												{% else %}
													<a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
												{% endif %}
											</li>
										{% endif %}
									{% endfor %}
								</ul>
							</nav>
							<!-- Section -->
								<section>
									<header class="major">
										<h2>Get in touch</h2>
									</header>
									<h5>비즈니스 제의 및 의견 공유는 아래로 해주세요.</h5>
									<ul class="contact">
										<li class="icon solid fa-envelope">youniyamii@gamil.com</a></li>
										<li class="icon solid fa-phone">+82-10-7628-6477</li>
										<li class="icon solid fa-home">1234 Somewhere Road<br />
										충청남도 천안시 동남구 상명대길 31</li>
									</ul>
								</section>

						</div>
					</div>
    </div>



    <!-- Scripts -->
    <script src="{% static 'teamangel/assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'teamangel/assets/js/jquery.min.js' %}"></script>
	<script src="{% static 'teamangel/assets/js/browser.min.js' %}"></script>
	<script src="{% static 'teamangel/assets/js/breakpoints.min.js' %}"></script>
	<script src="{% static 'teamangel/assets/js/util.js' %}"></script>
	<script src="{% static 'teamangel/assets/js/main.js' %}"></script>
</body>
</html>